import axios from "axios";
import { NextPage } from "next";
import Head from "next/head";
import { useEffect, useState } from "react";
import styles from '../../styles/Home.module.css'

type Movement = {
  id: number,
  data: string,
  importo: number,
  descrizione: string,
  categoriaId: number,
  tipologiaId: number,
  sorgente: number,
  destinazione: number,
  codice: string
}

const ViewMovements: NextPage = () => {
  const [movements, setMovements] = useState<Movement[]>([]);
  const [loading, setLoading] = useState<boolean>(true);
  const [errors, setErrors] = useState<any>(null);

  useEffect(() => {
    axios
      .get('/api/test')
      .then((res) => {
        console.log("ciao");
        setMovements(res.data);
        setLoading(false);
      })
      .catch((err) => {
        setErrors(err);
        setLoading(false);
      });
  }, []);

  return (
    <>
      <Head>
          <title>Visualizza Movimenti</title>
          <meta name="description" content="Generated by me" />
          <link rel="icon" href="/favicon.ico" />
          <base href="/movements/" />
      </Head>
      {!loading && 
        <div className={styles.container}>
          <p>Questi sono i codici</p>
          {movements.map(movement => <a href={movement.codice + "/"}>{movement.codice}</a>)}
        </div>
      }
      {loading && 
        <div>
          Caricamento...
        </div>
      }
    </>
  )
}

export default ViewMovements